//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalKermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecioDet
    {
        public int idListaPrecioDet { get; set; }
        public int listaPrecio { get; set; }
        public int producto { get; set; }
        public double precioVenta { get; set; }
    
        public virtual ListaPrecio ListaPrecio1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
