//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalKermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.IngresoComunidad = new HashSet<IngresoComunidad>();
            this.ListaPrecioDet = new HashSet<ListaPrecioDet>();
        }
    
        public int idProducto { get; set; }
        public Nullable<int> comunidad { get; set; }
        public Nullable<int> catProd { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public double precioVSugerido { get; set; }
        public int estado { get; set; }
    
        public virtual CategoriaProducto CategoriaProducto { get; set; }
        public virtual Comunidad Comunidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoComunidad> IngresoComunidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPrecioDet> ListaPrecioDet { get; set; }
    }
}
