//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalKermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RolUsuario
    {
        [Display(Name = "Id Rol Usuario")]
        public int idRolUsuario { get; set; }

        [Display(Name = "Usuario")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int usuario { get; set; }

        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int rol { get; set; }
    
        public virtual Rol Rol1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
