//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalKermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasaCambioDet
    {
        public int idTasaCambioDet { get; set; }
        public int tasaCambio { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal tipoCambio { get; set; }
        public int estado { get; set; }
    
        public virtual TasaCambio TasaCambio1 { get; set; }
    }
}
