//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalKermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TasaCambio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasaCambio()
        {
            this.TasaCambioDet = new HashSet<TasaCambioDet>();
        }

        [Display(Name = "Id Tasa Cambio")]
        public int idTasaCambio { get; set; }

        [Display(Name = "Moneda O")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int monedaO { get; set; }

        [Display(Name = "Moneda C")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int monedaC { get; set; }

        [Display(Name="Mes")]
        [DataType(DataType.Text, ErrorMessage = "Por favor ingrese un dato de tipo texto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(15, ErrorMessage = "Longitud máxima 15")]
        public string mes { get; set; }

        [Display(Name = "Año")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int anio { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int estado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambioDet> TasaCambioDet { get; set; }
    }
}
